/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import rojerusan.RSAnimation;

/**
 *
 * @author alber
 */
public class carga extends javax.swing.JFrame {
    // proceso de carga
    private Timer t;
    private int n = 0;
    
    
    
    public carga() {
        initComponents();
        
                // Textto de titulo
        setTitle("Carga de Aplicacion ");
          // Icono 
        setIconImage( new ImageIcon(getClass().getResource("/img/logosocabaya.png")).getImage());      
           //Inicia proceso de carga---------------------------------------------------------
        
        progreso.setValue(0);
        progreso.setColorBackground(new Color(0,0,0,0));
      //  pnlTexto.setBackground(new (0,0,0,0)); para dato de un textField
        
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this,false);
        // Area de deslizmiento x , y      setSubir
        RSAnimation.setBajar(-200 , 90 ,2,2,Circleloguin);

        
        // Implemntacion de clase abtracta
        ActionListener accion = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                               //throw new UnsupportedOperationException("Not supported yet."); 
                if(n <= 100){
                    progreso.setValue(n);
                    n = n +10;
                    
                }else {
                    t.stop();
                    dispose();
                    new formularios.loguin().setVisible(true);
                }
            }
            
        };
        // Establecer el tiempo
        t= new Timer ( 300,accion);
        t.start();
        
        //--------------------------------------------------------------------------------------        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        Circleloguin = new rojerusan.RSPanelCircleImage();
        progreso = new rojerusan.RSProgressBarSinText();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(0, 51, 0));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(0, 102, 51));
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Circleloguin.setImagen(new javax.swing.ImageIcon(getClass().getResource("/img/logosocabaya.png"))); // NOI18N

        javax.swing.GroupLayout CircleloguinLayout = new javax.swing.GroupLayout(Circleloguin);
        Circleloguin.setLayout(CircleloguinLayout);
        CircleloguinLayout.setHorizontalGroup(
            CircleloguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        CircleloguinLayout.setVerticalGroup(
            CircleloguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        rSPanelGradiente1.add(Circleloguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 93, -1, -1));

        progreso.setForeground(new java.awt.Color(0, 102, 51));
        progreso.setValue(10);
        progreso.setColorBorde(new java.awt.Color(0, 102, 51));
        progreso.setColorForeground(new java.awt.Color(0, 51, 0));
        rSPanelGradiente1.add(progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 608, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("SOCABAYA");
        rSPanelGradiente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 167));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Biblioteca Municipal de");
        rSPanelGradiente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 122, 256, 34));

        rSPanelShadow1.add(rSPanelGradiente1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSPanelCircleImage Circleloguin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private rojerusan.RSProgressBarSinText progreso;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables
}
